apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-archiver
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tekton-archiver
  template:
    metadata:
     labels:
       app.kubernetes.io/name: tekton-archiver
    spec:
      serviceAccountName: tekton-archiver
      containers:
        - name: tekton-archiver
          image: quay.io/kmcdermo/tekton-archiver:latest
          imagePullPolicy: Always
          args: ["archive"]
