apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-archiver
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tekton-archiver
  template:
    metadata:
     labels:
       app.kubernetes.io/name: tekton-archiver
    spec:
      serviceAccountName: tekton-archiver
      containers:
        - name: tekton-archiver
          image: quay.io/bigkevmcd/tekton-archiver:latest
          imagePullPolicy: Always
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: archiver-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: archiver-secret
                  key: AWS_REGION
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: archiver-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: archiver-secret
                  key: BUCKET_NAME
          args: ["archive"]
