apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-archiver
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-archiver
rules:
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  verbs:
  - create
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  - pods
  - pods/log
  verbs:
  - get
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-archiver
subjects:
- kind: ServiceAccount
  name: tekton-archiver
roleRef:
  kind: Role
  name: tekton-archiver
  apiGroup: rbac.authorization.k8s.io
